"""add column decan

Revision ID: 1b3e0d5d702b
Revises: e5f31f682543
Create Date: 2024-03-27 21:39:37.222545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3e0d5d702b'
down_revision: Union[str, None] = 'e5f31f682543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('decan', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty', 'decan')
    # ### end Alembic commands ###
